// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://treeoqilkxkwkfvzyppm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZWVvcWlsa3hrd2tmdnp5cHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODk5MjEsImV4cCI6MjA3MTg2NTkyMX0.XfXwbhk1rALJBvKt2RDqLInJ8u3T8x2WZ0vMxGQiqWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});